In [1]:
import cv2
import numpy as np
import pandas as pd

In [2]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eyes_cascade = cv2.CascadeClassifier("eyes.xml")
nose_cascade = cv2.CascadeClassifier("nose.xml")

img = cv2.imread('Before.png')
mustache = cv2.imread('mustache.png',-1)
glasses = cv2.imread('glasses.png',-1)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.cvtColor(img, cv2.COLOR_BGR2BGRA)#make picture gray
img

array([[[180, 202, 219, 255],
        [181, 203, 220, 255],
        [180, 202, 219, 255],
        ...,
        [175, 197, 215, 255],
        [174, 199, 216, 255],
        [173, 199, 214, 255]],

       [[180, 202, 219, 255],
        [181, 203, 220, 255],
        [180, 202, 219, 255],
        ...,
        [176, 198, 215, 255],
        [175, 199, 216, 255],
        [173, 199, 214, 255]],

       [[180, 202, 219, 255],
        [181, 203, 220, 255],
        [180, 202, 219, 255],
        ...,
        [176, 198, 215, 255],
        [175, 199, 216, 255],
        [173, 199, 214, 255]],

       ...,

       [[  1,   2,   6, 255],
        [  0,   1,   5, 255],
        [  1,   2,   6, 255],
        ...,
        [ 21,  21,  27, 255],
        [ 20,  20,  26, 255],
        [ 10,  10,  17, 255]],

       [[  2,   3,   7, 255],
        [  1,   2,   6, 255],
        [  0,   1,   5, 255],
        ...,
        [ 16,  16,  22, 255],
        [ 15,  15,  21, 255],
        [ 16,  16,  22, 255]],

       [[  2

In [3]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

for (x,y,w,h) in faces:
	roi_gray = gray[y:y+h, x:x+w]
	roi_color = img[y:y+h, x:x+w]
	#cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),2)


	eyes = eyes_cascade.detectMultiScale(roi_gray,1.3,5)
	
	for(ex,ey,ew,eh) in eyes:
		#cv2.rectangle(roi_color,(ex, ey), (ex+ew, ey+eh),(0,255,0),3)
		
		roi_eyes = roi_gray[ey:ey+eh, ex:ex+w]

		glasses2 = cv2.resize(glasses.copy(),(int(1.1*ew),int(2.5*eh)))
		print(glasses2.shape)
		gw, gh, gc = glasses2.shape
		for i in range(0,gw):
			for j in range(0,gh):
				if glasses2[i,j][3] != 0:
					roi_color[ ey - int(eh/1.5)+i, int(ex)+j] = glasses2[i, j]
	
	




	nose = nose_cascade.detectMultiScale(roi_gray, 1.3, 5)
	for (nx, ny, nw, nh) in nose:
		#cv2.rectangle(roi_color, (nx, ny), (nx + nw, ny + nh), (255, 0, 0), 3)
		roi_nose = roi_gray[ny: ny+nh, nx:nx+nw]
		mustache2 = cv2.resize(mustache.copy(),(nw,int(0.5*ny)))

		mw, mh, mc = mustache2.shape
		for i in range(0,mw):
			for j in range(0,mh):
				if mustache2[i,j][3] != 0:
					roi_color[ny + int(nh/1.5) + i, nx+j] = mustache2[i,j]

 

(192, 185, 4)


In [4]:
#Display resulting frame
img = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
cv2.imshow('Image',img)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)


img = np.reshape(img , (-1,3))
print((img))


cv2.waitKey(0)



cv2.destroyAllWindows()

[[219 202 180]
 [220 203 181]
 [219 202 180]
 ...
 [ 19  13  13]
 [ 21  15  15]
 [ 22  15  15]]


In [5]:
dfa = pd.DataFrame({"Prediction (R, G , B)" : list(img)})

In [6]:
dfa

Prediction (R, G , B)
0            [219, 202, 180]
1            [220, 203, 181]
2            [219, 202, 180]
3            [220, 203, 181]
4            [219, 202, 180]
...                      ...
182840          [23, 17, 17]
182841          [20, 14, 14]
182842          [19, 13, 13]
182843          [21, 15, 15]
182844          [22, 15, 15]

[182845 rows x 1 columns]

In [7]:
dfa.to_csv('ans_eyepair.csv',index = False)

In [8]:
df= pd.read_csv("ans_eyepair.csv")
df

Prediction (R, G , B)
0              [219 202 180]
1              [220 203 181]
2              [219 202 180]
3              [220 203 181]
4              [219 202 180]
...                      ...
182840            [23 17 17]
182841            [20 14 14]
182842            [19 13 13]
182843            [21 15 15]
182844            [22 15 15]

[182845 rows x 1 columns]